spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: controle-de-remedios

  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  security:
    user:
      name: dev_luanpaiva
      password: 565a2051-676b-4baf-bf51-2a0465b97a14

    jwt:
      secret: ${JWT_SECRET:6a7d4e8c1f9b3a5d7c8f6e1b2a4c9d7e3f8b5a0f1a6c4d9b8e8c9c5f95f0d2}

aws:
  region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
  s3:
    bucket: ${AWS_S3_BUCKET:}
    public-base-url: ${AWS_S3_PUBLIC_BASE_URL:}
