CREATE TYPE user_role AS ENUM (
    'ADMIN',
    'MANAGER',
    'PATIENT',
    'ASSISTANT'
);

CREATE TABLE users (
    id UUID PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(180) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'ASSISTANT',
    image_url VARCHAR(255),
    cpf VARCHAR(11) UNIQUE NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
